---
#---------------------------------------------------------
# Ansible Tower: 
# http://redhatgov.io/workshops/ansible_tower/
#---------------------------------------------------------

# Infrastructure
- name: Provision in AWS
  hosts: localhost
  roles:
    - aws-infra-role
  when: aws

- name: Provision in Azure
  hosts: localhost
  roles:
    - azure-infra-role
  when: azure

- name: Provision in GCC
  hosts: localhost
  roles:
    - gcc-infra-role
  when: gcc

# Workshop
- name: Ansible Tower | Configure nodes
  become: yes
  remote_user: "{{ system_user }}"
  hosts: tower_masters
  roles:
    - { role: subscription_manager }
    - { role: epel                 }
    - { role: nodejs               }
    - { role: ansible.tower        }
    - { role: zsh                  } 
    - { role: wetty                }
