---
# Workshop
- name: Ansible Tower Workshop | Configure nodes
  become: yes
  hosts: all
  roles:
    - { role: subscription-manager-role }
    - { role: epel-role                 }
    - { role: nodejs-role               }
    - { role: ansible-tower-role        }
    - { role: zsh-role                  } 
    - { role: wetty-role                }
