---
#---------------------------------------------------------
# Ansible Tower: 
# http://redhatgov.io/workshops/ansible_tower/
#---------------------------------------------------------

# Infrastructure
- name: Provision in AWS
  hosts: localhost
  become: no
  roles:
    - { role: aws-ansible-workshop-role, when: aws }

# - name: Provision in Azure
#   hosts: localhost
#   roles:
#     - { role: azure-infra-role, when: azure }

# - name: Provision in GCC
#   hosts: localhost
#   roles:
#      - { role: gcc-infra-role, when: gcc }


# Tower Inventory Sync
- name: Tower Inventory Sync
  hosts: localhost
  become: no
  roles:
    - { role: tower-inventory-role }

# Workshop
- name: Ansible Tower Workshop | Configure nodes
  become: yes
  remote_user: "{{ system_user }}"
  hosts: tower_masters
  roles:
    - { role: subscription-manager-role }
    - { role: epel-role                 }
    - { role: nodejs-role               }
    - { role: ansible-tower-role        }
    - { role: zsh-role                  } 
    - { role: wetty-role                }
