---
#---------------------------------------------------------
# Strangling the Monolith: 
# http://redhatgov.io/workshops/strangling_the_monolith/
#---------------------------------------------------------
# Infrastructure
- name: Provision in AWS
  hosts: localhost
  roles:
    - aws-infra-role
  when: aws

- name: Provision in Azure
  hosts: localhost
  roles:
    - azure-infra-role
  when: azure

- name: Provision in GCC
  hosts: localhost
  roles:
    - gcc-infra-role
  when: gcc

# Workshop
- name: OpenShift | Pre-installation
  hosts: openshift_masters, openshift_nodes
  become: yes
  roles:
    - openshift.prereq

- name: OpenShift | Advanced installation
  hosts: openshift_masters
  roles:
    - openshift.install

- name: OpenShift | Configure cluster
  hosts: openshift_masters
  become: yes
  roles:
    - openshift.config