---
#---------------------------------------------------------
# OpenShift 101: 
# http://redhatgov.io/workshops/openshift_101_dcmetromap/
#---------------------------------------------------------

# Infrastructure
- name: Provision in AWS
  hosts: localhost
  roles:
    - aws-infra-role
  when: aws

- name: Provision in Azure
  hosts: localhost
  roles:
    - azure-infra-role
  when: azure

- name: Provision in GCC
  hosts: localhost
  roles:
    - gcc-infra-role
  when: gcc

# Workshop
- name: OpenShift | Pre-installation
  hosts: masters, nodes
  become: yes
  roles:
    - openshift-prereq-role

- name: OpenShift | Advanced installation
  hosts: masters
  roles:
    - openshift-install-role

- name: OpenShift | Configure cluster
  hosts: masters
  become: yes
  roles:
    - openshift-config-role

- name: OpenShift | Wetty
  hosts: wetty
  become: yes
  roles:
    - { role:  epel-role      }
    - { role: nodejs-role     }
    - { role: wetty-role      }
    - { role: oc-role         }
    - { role: zsh-role        }
    