---
#---------------------------------------------------------
# Secure Containers: 
# http://redhatgov.io/workshops/security_containers
#---------------------------------------------------------

# Infrastructure
- name: Provision in AWS
  hosts: localhost
  roles:
    - aws-infra-role
  when: aws

- name: Provision in Azure
  hosts: localhost
  roles:
    - azure-infra-role
  when: azure

- name: Provision in GCC
  hosts: localhost
  roles:
    - gcc-infra-role
  when: gcc

# Workshop
- name: Secure Containers | Configure instances
  remote_user: "{{ system_user }}"
  hosts: sec_nodes 
  become: yes
  roles:
    - { role: subscription-manager-role         }
    - { role: ansible-ssh-pipelining-role       }
    - { role: docker-role                       }
    - { role: jq-role                           }
    - { role: epel-role                         } 
    - { role: cockpit-role                      }
    - { role: secure-containers-role            }
    - { role: zsh-role                          }
    - { role: nodejs-role                       }
    - { role: wetty-role                        }